### ISSUE TITLE
Release checklist for v1.65.1 (scheduled)

### ISSUE THREAD

**Issue by jhnstn** [jhnstn/gutenberg-mobile#13]
# Release Checklist
This checklist is for the scheduled release v1.65.1.

 **Release date:** 2021-11-11

## Pre release

- [ ] Review [Release process notes](#)
- [ ] [Notifiy open Gutenberg Mobile PRs assigned to 1.65.1 milestone](https://github.com/jhnstn/gutenberg-mobile/milestone/1).
<details>
<summary>Message Template</summary>
<p>

```markdown
Hello!
We will cut the 1.65.1 release on 2021-11-11.
I plan to circle back and bump this PR to the next milestone then,
but please let me know if you’d rather us work to include this PR in 1.65.1.
Thanks!
```

</p>
</details>

- [ ] Create WPiOS and WPAndroid builds from `develop` and complete the [general writing flow tests](https://href.li/?https://github.com/wordpress-mobile/test-cases/tree/master/test-cases/gutenberg/writing-flow).
- [ ] Clone or update the [release toolkit](https://href.li/?https://github.com/wordpress-mobile/release-toolkit-gutenberg-mobile) and review the [release script instructions](https://href.li/?https://github.com/wordpress-mobile/release-toolkit-gutenberg-mobile/blob/develop/Releasing.md).

## Create the Release

On 2021-11-11:

- [ ] [Verify Aztec is up to date](#).
- [ ] Run `./release_automation.sh` from the release toolkit to generate the main apps integration PRs [\*](#).
- [ ] Notify team that the release has been cut.
<details>
<summary>Message Template</summary>
<p>

```markdown
⚠️ The gutenberg-mobile {{release_version}} release branches are now cut.
Please do not merge any Gutenberg-related changes into the WPiOS or WPAndroid
develop branches until after the main apps cut their own releases next week.
If you’d like to merge changes now, merge them into the gutenberg/after\_{{release_version}} branches.
```

</p>
</details>

- [ ] [Verify localization string files have been generated properly](#).
- [ ] Update `Unreleased` section in [`RELEASE-NOTES.txt`](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/RELEASE-NOTES.txt) and [`gutenberg/../CHANGELOG.md`](https://github.com/WordPress/gutenberg/blob/trunk/packages/react-native-editor/CHANGELOG.md). Add a new `Unreleased` section after updating the release notes.
- [ ] Perform quick smoke test of the editor on both iOS and Android builds
- [ ] Update [Gutenberg Mobile PR](https://github.com/wordpress-mobile/gutenberg-mobile/pulls?q=is%3Apr+is%3Aopen+label%3Arelease-process) description. Make sure the "Changes" section informs testers on what is in the release.
- [ ] Mark all 4 PRs ready for review.

## Integrate the Release

On 2021-11-11:

- [ ] Verify `gutenberg` ref within the gutenberg-mobile release branch is pointing to the [latest commit](#) in Gutenberg release branch.
- [ ] Create and push a `rnmobile/1.65.1` git tag for the head of [Gutenberg release branch](https://github.com/WordPress/gutenberg/branches/all?query=rnmobile%2Frelease).
- [ ] [Update bundles in the Gutenberg Mobile release branch](#).
- [ ] Merge **gutenberg-mobile** PR to `trunk` [using the "Create a merge commit" option](#). **WARNING** do **not** merge gutenberg PR to `trunk` yet.
- [ ] [Create a new Gutenberg moble release](#).
- [ ] [Update Gutenberg mobile references in the main apps](#).
- [ ] Re-run optional tests on main apps PRs.
- [ ] Merge main apps PSs to the respective `develop` branches.
- [ ] Notify team that the release is now in the main apps `develop` branches
<details>
<summary>Message Template</summary>
<p>

```markdown
Hey team. I wanted to let you know that the mobile Gutenberg team has finished integrating
the 1.65.1 Gutenberg release into the WPiOS and WPAndroid `develop` branches.
The integration is ready for the next release cut/build creation when you are available.
Please let me know if you have any questions. Thanks!
```

</p>

</details>

## Sync Release

- [ ] Merge release changes back to `gutenberg-mobile/develop` e.g. `trunk -> merge_release_1.65.1_to_develop -> develop`
- [ ] Reslove any conflicts and merge `gutenberg/rnmobile/release_{{release_version}}` PR to `gutenberg/trunk`.
- [ ] Update `gutenberg` reference in `gutenberg-mobile/merge_release_1.65.1_to_develop` to point to `gutenberg/trunk`.
- [ ] Merge `gutenberg-mobile/merge_release_1.65.1_to_develop` PR to `gutenberg/develop`.

## Clean Up Pending Work

⚠️ This section may only be completed after the main apps cut their own release branches.

- [ ] Open a PR to merge `gutenberg/after_1.65.1` into `gutenberg-mobile/develop`.
- [ ] Merge or Close`gutenberg/after_1.65.1` **AFTER** the main apps have cut release branches.

## Test the Release

Use the main WP apps to complete the following tests:

#### iOS

- [ ] Test new [changes in the release](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/RELEASE-NOTES.txt)
- [ ] Complete the [general writing flow tests].(https://github.com/wordpress-mobile/test-cases/tree/master/test-cases/gutenberg/writing-flow
- [ ] Complete the [Unsupported Block Editor test cases](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/unsupported-block-editing.md#unsupported-block-editing---test-cases).
- [ ] Complete the [Sanity Tests](https://href.li/?https://github.com/wordpress-mobile/test-cases/blob/trunk/test-suites/gutenberg/sanity-test-suites.md)

#### Android

- [ ] Test new [changes in the release](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/RELEASE-NOTES.txt)
- [ ] Complete the [general writing flow tests].(https://github.com/wordpress-mobile/test-cases/tree/master/test-cases/gutenberg/writing-flow
- [ ] Complete the [Unsupported Block Editor test cases](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/unsupported-block-editing.md#unsupported-block-editing---test-cases).
- [ ] Complete the [Sanity Tests](https://href.li/?https://github.com/wordpress-mobile/test-cases/blob/trunk/test-suites/gutenberg/sanity-test-suites.md)

## Finish the Release

  
- [ ] Notify the next release wranglers with a **tentive schedule** for the next release.

- [ ] Celebrate! 🎉
