### ISSUE TITLE
Release checklist for v1.65.1 (hotfix)

### ISSUE THREAD

**Issue by jhnstn** [jhnstn/gutenberg-mobile#14]
# Release Checklist
This checklist is for the hotfix release v1.65.1.

 **Release date:** 2021-11-11

## Create the Release

On 2021-11-11:

- [ ] [Verify Aztec is up to date](#).
- [ ] Run `./release_automation.sh` from the release toolkit to generate the main apps integration PRs [\*](#).
- [ ] Notify team that the release has been cut.
<details>
<summary>Message Template</summary>
<p>

```markdown
⚠️ The gutenberg-mobile 1.65.1 release branches are now cut.
Please do not merge any Gutenberg-related changes into the WPiOS or WPAndroid
develop branches until after the main apps cut their own releases next week.
If you’d like to merge changes now, merge them into the gutenberg/after\_1.65.1 branches.
```

</p>
</details>

- [ ] [Verify localization string files have been generated properly](#).
- [ ] Update `Unreleased` section in [`RELEASE-NOTES.txt`](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/RELEASE-NOTES.txt) and [`gutenberg/../CHANGELOG.md`](https://github.com/WordPress/gutenberg/blob/trunk/packages/react-native-editor/CHANGELOG.md). Add a new `Unreleased` section after updating the release notes.
- [ ] Perform quick smoke test of the editor on both iOS and Android builds
- [ ] Update [Gutenberg Mobile PR](https://github.com/wordpress-mobile/gutenberg-mobile/pulls?q=is%3Apr+is%3Aopen+label%3Arelease-process) description. Make sure the "Changes" section informs testers on what is in the release.
- [ ] Mark all 4 PRs ready for review.
- [ ] Celebrate! 🎉
