### ISSUE TITLE
Release checklist for v1.66.0 (scheduled)

### ISSUE THREAD

**Issue by jhnstn** [jhnstn/gutenberg-mobile#31]
# Release Checklist
This checklist is for the scheduled release v1.66.0.

 **Release date:** 2021-11-11

## Before the Release (2021-11-11)

- [ ] Review the [release documentation](https://github.com/wordpress-mobile/release-toolkit-gutenberg-mobile/blob/develop/Releasing.md).
- [ ] [Notifiy open Gutenberg Mobile PRs assigned to 1.66.0 milestone](https://github.com/jhnstn/gutenberg-mobile/milestone/3).
<details>
<summary>Message Template</summary>
<p>

```markdown
Hello!
We will cut the 1.66.0 release on 2021-11-11.
I plan to circle back and bump this PR to the next milestone then,
but please let me know if you’d rather us work to include this PR in 1.66.0.
Thanks!
```

</p>
</details>
- [ ] Clone or update the [release toolkit](https://github.com/wordpress-mobile/release-toolkit-gutenberg-mobile)
- [ ] Create WPiOS and WPAndroid builds from `develop`.
- [ ] [Perform general writing flow tests on Android](https://github.com/wordpress-mobile/test-cases/tree/master/test-cases/gutenberg/writing-flow).
- [ ] [Perform general writing flow tests on iOS](https://github.com/wordpress-mobile/test-cases/tree/master/test-cases/gutenberg/writing-flow).

## Create the Release (2021-11-11)

- [ ] [Verify Aztec is up to date](https://github.com/wordpress-mobile/release-toolkit-gutenberg-mobile/blob/develop/Releasing.md#handling-aztec-updates).
- [ ] Run `./release_automation.sh` from the release toolkit to generate the main apps integration PRs [\*](#).
- [ ] Notify team that the release has been cut.
<details>
<summary>Message Template</summary>
<p>

```markdown
⚠️ The gutenberg-mobile 1.66.0 release branches are now cut.
Please do not merge any Gutenberg-related changes into the WPiOS or WPAndroid
develop branches until after the main apps cut their own releases next week.
If you’d like to merge changes now, merge them into the `gutenberg/after_1.66.0` branches.
```

</p>
</details>

- [ ] [Verify localization string files have been generated properly](https://github.com/wordpress-mobile/release-toolkit-gutenberg-mobile/blob/develop/Releasing.md).
- [ ] Update `Unreleased` section in [`RELEASE-NOTES.txt`](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/RELEASE-NOTES.txt) and [`gutenberg/../CHANGELOG.md`](https://github.com/WordPress/gutenberg/blob/trunk/packages/react-native-editor/CHANGELOG.md). Add a new `Unreleased` section after updating the release notes.
- [ ] Perform quick smoke test of the editor on both iOS and Android builds
- [ ] Update [Gutenberg Mobile PR](https://github.com/wordpress-mobile/gutenberg-mobile/pulls?q=is%3Apr+is%3Aopen+label%3Arelease-process) description. Make sure the "Changes" section informs testers on what is in the release.
- [ ] Mark all 4 PRs ready for review.

## Integrate the Release (2021-11-11)

- [ ] Verify `gutenberg` ref within the gutenberg-mobile release branch is pointing to the [latest commit](#) in Gutenberg release branch.
- [ ] Create and push a `rnmobile/1.66.0` git tag for the head of [Gutenberg release branch](https://github.com/WordPress/gutenberg/branches/all?query=rnmobile%2Frelease).
- [ ] [Update bundles in the Gutenberg Mobile release branch](#).
- [ ] Merge **gutenberg-mobile** PR to `trunk` [using the "Create a merge commit" option](#). **WARNING** do **not** merge gutenberg PR to `trunk` yet.
- [ ] [Create a new Gutenberg moble release](#).
- [ ] [Update Gutenberg mobile references in the main apps](#).
- [ ] Re-run optional tests on main apps PRs.
- [ ] Merge main apps PRs to the respective develop branches.
- [ ] Notify team that the release is now in the main apps develop branches.

<details>
<summary>Message Template</summary>
<p>

```markdown
Hey team. I wanted to let you know that the mobile Gutenberg team has finished integrating
the 1.66.0 Gutenberg release into the WPiOS and WPAndroid `develop` branches.
The integration is ready for the next release cut/build creation when you are available.
Please let me know if you have any questions. Thanks!
```

</p>

</details>

- [ ] Notify the next release wranglers with a **tentative schedule** for the next release.

- [ ] Celebrate! 🎉
