### ISSUE TITLE
Release checklist for v1.65.1 (scheduled)

### ISSUE THREAD

**Issue by jhnstn** [jhnstn/gutenberg-mobile#9]
This checklist is for the scheduled release v1.65.1.

 **Release date:** 2021-11-11

### Pre release

- [ ] Review [Release process notes](#)
- [ ] [Notifiy open Gutenberg Mobile PRs assigned to 1.65.1 milestone](https://github.com/jhnstn/gutenberg-mobile/milestone/1).
<details>
<summary>Message Template</summary>
<p>

```markdown
Hello!
We will cut the 1.65.1 release on 2021-11-11.
I plan to circle back and bump this PR to the next milestone then,
but please let me know if you’d rather us work to include this PR in 1.65.1.
Thanks!
```

</p>
</details>

- [ ] Create WPiOS and WPAndroid builds from `develop` and complete the [general writing flow tests](https://href.li/?https://github.com/wordpress-mobile/test-cases/tree/master/test-cases/gutenberg/writing-flow).
- [ ] Clone or update the [release toolkit](https://href.li/?https://github.com/wordpress-mobile/release-toolkit-gutenberg-mobile) and review the [release script instructions](https://href.li/?https://github.com/wordpress-mobile/release-toolkit-gutenberg-mobile/blob/develop/Releasing.md).

### Create the Release

On 2021-11-11:

- [ ] [Verify Aztec is up to date](#).
- [ ] Run `./release_automation.sh` from the release toolkit to generate the main apps integration PRs [\*](#).
- [ ] Notify team that the release has been cut.
<details>
<summary>Message Template</summary>
<p>

```markdown
⚠️ The gutenberg-mobile {{release_version}} release branches are now cut. Please do not merge any Gutenberg-related changes into the WPiOS or WPAndroid develop branches until after the main apps cut their own releases next week. If you’d like to merge changes now, merge them into the gutenberg/after\_{{release_version}} branches.
```

</p>
</details>
- [ ] [Verify localization string files have been generated properly](#).
- [ ] Update `Unreleased` section in [`RELEASE-NOTES.txt`](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/RELEASE-NOTES.txt) and [`gutenberg/../CHANGELOG.md`](https://github.com/WordPress/gutenberg/blob/trunk/packages/react-native-editor/CHANGELOG.md). Add a new `Unreleased` section after updating the release notes.
- [ ] Perform quick smoke test of the editor on both iOS and Android builds
- [ ] Update [Gutenberg Mobile PR](https://github.com/wordpress-mobile/gutenberg-mobile/pulls?q=is%3Apr+is%3Aopen+label%3Arelease-process) description. Make sure the "Changes" section informs testers on what is in the release.
- [ ] Mark all 4 PRs ready for review.
  
- [ ] Notify the next release wranglers with a **tentive schedule** for the next release.

- [ ] Celebrate! 🎉
